spiral/spiral/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
    #Panel de administracion
    url(r'^panel/', include('apps.sp.urls.panel')),

    #Registro de modelos
    url(r'^', include('apps.sp.urls.website.home')),

    # url(r'^$', lambda x: HttpResponseRedirect('/upload/new/')),
    url(r'^upload/', include('apps.fileupload.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

spiral/apps/sp/models/Bank.py
from django.db import models


class Bank(models.Model):

    STATUS_ACTIVE = 1
    STATUS_DELETE = 2
    STATUS_INACTIVE = 3
    CHOICE_STATUS = (
        (STATUS_ACTIVE, 'Activo'),
        (STATUS_INACTIVE, 'Inactivo'),
        (STATUS_DELETE, 'Eliminado')
    )

    name = models.CharField(
        verbose_name='Nombre',
        max_length=70
    )

    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Brand.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Brand(models.Model):
    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE, _(u'inactivo')),
        (STATUS_ACTIVE, _(u'activo'))
        )

    name = models.CharField(
        max_length = 45
        )
    entry = models.ForeignKey(
        'Entry',
        related_name='brand_set',
        )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
        )
    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
        )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Broadcast.py
from django.db import models


class Broadcast(models.Model):

    STATUS_ACTIVE = 1
    STATUS_DELETE = 2
    STATUS_INACTIVE = 3
    CHOICE_STATUS = (
        (STATUS_ACTIVE, 'Activo'),
        (STATUS_INACTIVE, 'Inactivo'),
        (STATUS_DELETE, 'Eliminado')
    )

    name = models.CharField(
        verbose_name='Nombre',
        max_length=70
    )

    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Casting.py
from django.db import models


class Casting(models.Model):

    project = models.OneToOneField(
        'Project',
        primary_key=True
    )

    ppi = models.DateField(
        verbose_name='PPI',
        null=True,
    )

    realized = models.DateField(
        verbose_name='Realizacion',
        null=True,
    )

    ppg = models.DateField(
        verbose_name='PPG',
        null=True,
    )

    type_casting = models.ManyToManyField(
        'TypeCasting',
        verbose_name='Tipo de casting',
    )

    class Meta:
        app_label = 'sp'

    @classmethod
    def get_detail_data(self, project):
        casting = Casting.objects.get(project=project)
        detail_model = CastingDetailModel.objects.filter(casting=casting)
        data = []
        for detail in detail_model:
            quantity_participate = CastingDetailParticipate.objects.filter(detail_model_id=detail.id).count()
            data.append({
                'id': detail.id,
                'cant': detail.quantity,
                'avaible': detail.quantity - quantity_participate,
                'profile': detail.profile,
                'model': detail.feature,
                'character': detail.get_character_display()
            })
        return data


class TypeCasting(models.Model):

    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE, 'inactivo'),
        (STATUS_ACTIVE, 'activo')
    )

    name = models.CharField(
        verbose_name='Nombre',
        max_length=45
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )
    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'


class CastingDetailModel(models.Model):

    CHARACTER_PRINCIPAL = 1
    CHARACTER_SECONDARY = 0
    CHOICE_CHARACTER = (
        (CHARACTER_PRINCIPAL, 'Principal'),
        (CHARACTER_SECONDARY, 'Secundario')
    )

    casting = models.ForeignKey(
        'Casting',
        related_name='casting_detail_model_set',
    )

    quantity = models.SmallIntegerField()

    profile = models.CharField(
        verbose_name='Perfil',
        max_length=100
    )

    feature = models.CharField(
        verbose_name='Carracteristicas',
        max_length=200,
        null=True
    )

    character = models.SmallIntegerField(
        choices=CHOICE_CHARACTER,
        default=CHARACTER_PRINCIPAL,
        null=True
    )

    type_casting = models.ManyToManyField(
        'TypeCasting',
        verbose_name='Tipo de casting',
        null=True
    )

    scene = models.CharField(
        verbose_name='Escena',
        max_length=100,
        null=True
    )

    budget = models.DecimalField(
        verbose_name='Presupuesto',
        max_digits=10,
        decimal_places=2,
        null=True
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    def __unicode__(self):
        return '%s %s' %(self.quantity, self.profile)

    class Meta:
        app_label = 'sp'


class CastingDetailParticipate(models.Model):

    detail_model = models.ForeignKey(
        'CastingDetailModel',
        related_name='casting_detail_participate_set',
    )

    model = models.ForeignKey(
        'Model',
        related_name='casting_detail_participate_set',
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    def __unicode__(self):
        return self.model.name_complete

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/City.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class City(models.Model):

    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE,_(u'inactivo')),
        (STATUS_ACTIVE, _(u'activo'))
    )

    country = models.ForeignKey(
        'country',
        verbose_name=_(u'Pais'),
        related_name='city_set',
    )

    name = models.CharField(
        max_length=45
    )
    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Client.py
from django.db import models


class TypeClient(models.Model):

    name = models.CharField(
        max_length=60,
        verbose_name='Tipo de Cliente',
        )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'


class Client(models.Model):

    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    STATUS_ABROAD = 2
    STATUS_FAKE = 3
    CHOICE_STATUS = (
        (STATUS_INACTIVE, 'inactivo'),
        (STATUS_ACTIVE, 'activo'),
        (STATUS_ACTIVE, 'extranjero')
    )

    name = models.CharField(
        max_length=60,
        verbose_name='Razon Social',
    )

    ruc = models.CharField(
        max_length=11,
        verbose_name='R.U.C',
        unique=True
    )

    address = models.CharField(
        max_length=70,
        verbose_name='Direccion',
        null=True
    )

    type_client = models.ManyToManyField(TypeClient)

    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE,
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Commercial.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
import urllib2
from django.utils import simplejson

from apps.sp.models.Project import Project


class Commercial(models.Model):
    STATUS_TERMINATE = 2
    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE,_(u'Inactivo')),
        (STATUS_TERMINATE,_(u'Terminado')),
        (STATUS_ACTIVE, _(u'Activo'))
    )

    name = models.CharField(
        verbose_name=_(u'Nombre'),
        max_length=50
    )

    brand = models.ForeignKey(
        'Brand',
        verbose_name=_(u'Marca'),
        related_name='commercial_set',
    )
    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

    def get_data_api_json(self):
        if self.project.project_code is not None:
            try:
                op = self.project.project_code[5:6]
                if op == "M":
                    url = 'http://192.168.1.3/sistemas/sisadmini/api/proyecto.php?codigo='+self.model_code
                else:
                    url = 'http://192.168.1.3/sistemas/barranco/api/proyecto.php?codigo='+self.model_code+'&'+'op='+op

                req = urllib2.Request(url, None, {'user-agent':'syncstream/vimeo'})
                opener = urllib2.build_opener()
                f = opener.open(req,timeout=1)
                api = simplejson.load(f)
                data = {
                    'nombre':api.get('nombre', None),
                    'productora':api.get('productora', None),
                    'agencia':api.get('agencia', None),
                    'realizadora': api.get('realizadora', None),
                    'response': True
                }
                return data
            except:
                pass

        data = {
            'response': False
        }
        return data

    @staticmethod
    def get_commercial_tag():
        return 'commercial_list'

    @property
    def realized(self):
        date = ''
        for detail in self.commercial_date_detail_set.all():
            date = date + detail.date.strftime("%d/%m/%Y") + ' | '
        return date

    @property
    def project(self):
        project = Project.objects.filter(commercial=self).exists()
        project = Project.objects.filter(commercial=self).exclude(status=Project.STATUS_DELETE) if project else 'Ninguno'
        if project == 'Ninguno':
            return project
        if len(project) == 1:
            return project[0].get_code()
        else:
            return None


class CommercialDateDetail(models.Model):

    commercial = models.ForeignKey(
        'commercial',
        verbose_name='Comercial',
        related_name='commercial_date_detail_set'
    )

    date = models.DateField(
        verbose_name='Fecha del comercial',
        null=False,
    )

    def __unicode__(self):
        return '%s %s' %(self.commercial, self.date)

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Company.py
from django.db import models


class Company(models.Model):

    STATUS_ACTIVE = 1
    STATUS_DELETE = 2
    STATUS_INACTIVE = 3
    CHOICE_STATUS = (
        (STATUS_ACTIVE, 'extra'),
        (STATUS_INACTIVE, 'casting'),
        (STATUS_DELETE, 'casting')
    )

    name = models.CharField(
        verbose_name='Nombre',
        max_length=70
    )

    ruc = models.CharField(
        verbose_name='RUC',
        max_length=10,
    )

    address = models.CharField(
        verbose_name='Direccion',
        max_length=100,
    )

    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    def __unicode__(self):
        return '%s %s' %(self.name, self.ruc)

    class Meta:
        app_label = 'sp'


class CompanyDetailAccount(models.Model):

    bank = models.ForeignKey(
        'Bank',
        verbose_name='Banco',
        related_name='company_detail_account_set'
    )

    account = models.CharField(
        verbose_name='Numero de cuenta',
        max_length=30,
    )

    def __unicode__(self):
        return '%s %s' %(self.bank.name, self.account)

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Contract.py
from django.db import models
from apps.sp.models.Country import Country
from django.utils.translation import ugettext_lazy as _


class Contract(models.Model):

    TYPE_PHOTO = 2
    TYPE_VIDEO = 1

    CHOICE_TYPE = (
        (TYPE_PHOTO,_(u'Foto')),
        (TYPE_VIDEO, _(u'Video'))
    )

    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE,_(u'inactivo')),
        (STATUS_ACTIVE, _(u'activo'))
        )

    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=TYPE_VIDEO
        )

    period_date = models.CharField(
        max_length=50,
        verbose_name=_(u'periodo de contrato (meses)'),
    )


    start_contract = models.DateField(
        verbose_name=_(u'Inicio del contrato'),
        null=False,
    )

    end_contract = models.DateField (
        verbose_name=_(u'Final del contrato'),
        null=False,
    )

    country = models.ManyToManyField(Country)

    type_contract =  models.ForeignKey(
        'TypeContract',
        verbose_name='tipo de contrato',
        related_name='contract_set',
        null=True
    )

    duration_month = models.IntegerField(
        editable=False,
        null=False,
        default=0
    )
    broadcast = models.ManyToManyField(
        'Broadcast',
        verbose_name='Medios',
        null=True
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    class Meta:
        app_label = 'sp'


class TypeContract(models.Model):
    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE, _(u'inactivo')),
        (STATUS_ACTIVE, _(u'activo'))
    )

    name = models.CharField(
        max_length=45
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )
    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Country.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Country(models.Model):

    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE,_(u'inactivo')),
        (STATUS_ACTIVE, _(u'activo'))
    )
    name = models.CharField(
        max_length=45
    )
    nationality = models.CharField(
        max_length=45
    )
    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/Currency.py
from django.db import models


class Currency(models.Model):

    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 0
    CHOICE_STATUS = (
        (STATUS_INACTIVE, 'inactivo'),
        (STATUS_ACTIVE, 'activo')
    )
    symbol = models.CharField(
        verbose_name='Simbolo',
        max_length=5
    )

    name = models.CharField(
        verbose_name='Nombre',
        max_length=45
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )
    status = models.SmallIntegerField(
        choices=CHOICE_STATUS,
        default=STATUS_ACTIVE
    )

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'sp'

spiral/apps/sp/models/ModelHasCommercial.py
from django.db import models


class ModelHasCommercial(models.Model):

    model = models.ForeignKey(
        'Model',
        related_name='model_has_commercial_set'
    )

    commercial = models.ForeignKey(
        'Commercial',
        related_name='model_has_commercial_set'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    modified = models.DateTimeField(
        editable=False,
        auto_now=True
    )

    class Meta:
        app_label = 'sp'

spiral/apps/sp/templates/panel/message/create.html
{% extends 'panel/panel_basev3.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
    {% block extra_style %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/chosen.css" type="text/css" />
    {% endblock %}

{% block content %}

    <div class="page-header">
            <h2>{% trans "Nueva Marca:" %}</h2>
    </div>
      <form method="post" action="" class="form-horizontal">
          {% csrf_token %}

          {% crispy form %}
          <div class="form-actions">
              <a class="btn" href="{% url "message_list" %}">{% trans 'Cancelar' %}</a> o
              <input type="submit" class="btn btn-inverse" value="{% trans 'Crear'%}" />
          </div>
      </form>
{% endblock %}

{% block script_bottom %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/chosen.jquery.js"></script>
    <script>
        $(document).on('ready',function(){
            $('#id_entry').addClass('chzn-select');
            $('#id_entry').chosen({});
        });
    </script>
{% endblock %}

spiral/apps/sp/templates/panel/message/delete.html
{% extends 'panel/panel_basev3.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

     <div class="page-header">
         <h2>{% trans "Está seguro de eliminar esta marca: " %} {{ object.name }} {% trans " ?" %}</h2>
     </div>

      <form method="post" action="" class="">
          {% csrf_token %}
          <div class="form-actions">
              <a class="btn" href="{% url "message_list" %}">{% trans 'Cancelar' %}</a> o
              <input type="submit" class="btn btn-danger" value="{% trans 'Eliminar' %}" />
          </div>
      </form>
{% endblock %}

spiral/apps/sp/templates/panel/message/list.html
{% extends 'panel/panel_basev3.html' %}
{% load i18n %}
{% load common_tags %}
{% load crispy_forms_tags %}

    {% block extra_style %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/chosen.css" type="text/css" />
        <style>
            .tools {
                float: right !important;
            }
        </style>
    {% endblock %}

{% block content %}
    <div class="page-header">
        <div class="tools">
            <a href="{%   url "message_create" %}" class="btn btn-success">
                <i class="icon-plus icon-white"></i> {% trans 'Nueva Plantilla' %}</a>
        </div>
        <h2>{%  trans 'Plantillas registradas' %}</h2>
    </div>
    <ul class="nav nav-pills">
      <li class="active">
        <a href="#" id="hide-show-search">Mostrar / Ocultar</a>
      </li>
    </ul>
    <div id="search-form">
        <form method="get" action="" class="form-horizontal well well-small search-form">
            <div class="row-fluid">
                {% crispy search_form %}
                <div class="form-actions">
                    <input type="submit" class="btn" value="{% trans 'Search' %}">
                </div>
            </div>
        </form>
    </div>

    <div class="row-fluid">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Titulo' %}</th>
                    <th>{% trans 'Asunto' %}</th>
                    <th>{% trans 'Opciones' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for message in object_list %}
                <tr>
                    <td>{{ message.name }}</td>
                    <td>{{ message.subject }}</td>
                    <td><a href="{% url "message_edit" message.pk %}">{% trans 'Update' %}</a> |
                        <a href="{% url "message_delete" message.pk %}">{% trans 'Delete' %}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% url 'message_list' as page_url %}
    {% pagination_ctl page_obj url=page_url url_args=search_url_params %}
    </div>
{% endblock %}

{% block script_bottom %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/chosen.jquery.js"></script>
    <script>
        $(document).on('ready',function(){
            $('#id_entry_id').addClass('chzn-select');
            $('#id_entry_id').chosen({});
            $('#hide-show-search').click(function(){
                $('#search-form').toggle('fade');
            });
        });
    </script>

{% endblock %}

spiral/apps/sp/templates/panel/message/update.html
{% extends 'panel/panel_basev3.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

    {% block extra_style %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/chosen.css" type="text/css" />
    {% endblock %}
s
{% block content %}

    <div class="page-header">
            <h2>{% trans  'Actualizar marca:'  %} {{ object.name }}</h2>
    </div>

      <form method="post" action="" class="form-horizontal">
          {% csrf_token %}

          {% crispy form %}

          <div class="form-actions">
                    <a class="btn" href="{% url "message_list" %}">{% trans 'Cancelar' %}</a> o
                    <input type="submit" class="btn btn-inverse" value="{% trans 'Actualizar' %}" />
          </div>

        </form>
{% endblock %}

{% block script_bottom %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/chosen.jquery.js"></script>
    <script>
        $(document).on('ready',function(){
            $('#id_entry').addClass('chzn-select');
            $('#id_entry').chosen({});
        });
    </script>
{% endblock %}